"""The connectors this platform knows how to offer.

Reference data, not user state. It lived in config/connectors.json alongside a
`connected` boolean per row, which is why flipping one connector's state meant
rewriting the entire catalog. The catalog is code now, reviewable in a diff;
whether a connector is connected, and which agents use it, lives in the database.

Shaped like personas.BUILT_IN: a floor that stored records layer on top of.
"""

CATALOG: tuple[dict, ...] = tuple(
[   {   'id': 'slack',
        'name': 'Slack',
        'slug': 'slack',
        'category': 'Communication',
        'description': 'Send messages, monitor workspace channels, search conversations, and '
                       'post alerts.',
        'recommended': True,
        'color': '#4A154B',
        'icon': 'slack',
        'tools': [   'send_message',
                     'search_messages',
                     'list_channels',
                     'add_reaction',
                     'get_thread']},
    {   'id': 'gmail',
        'name': 'Gmail',
        'slug': 'ac_DFSagMjeXO9u',
        'toolkit': 'gmail',
        'category': 'Productivity',
        'description': 'Search inbox emails, read conversation threads, draft responses, and '
                       'send emails directly through Google Workspace.',
        'recommended': True,
        'color': '#EA4335',
        'icon': 'gmail',
        'tools': [   'send_email',
                     'fetch_emails',
                     'search_emails',
                     'create_draft',
                     'get_thread_messages',
                     'list_labels']},
    {   'id': 'googlecalendar',
        'name': 'Google Calendar',
        'slug': 'googlecalendar',
        'category': 'Productivity',
        'description': 'Check availability, schedule calendar events, reschedule meetings, and '
                       'send invites.',
        'recommended': True,
        'color': '#4285F4',
        'icon': 'googlecalendar',
        'tools': [   'create_event',
                     'list_events',
                     'find_free_slots',
                     'update_event',
                     'delete_event']},
    {   'id': 'github',
        'name': 'GitHub',
        'slug': 'github',
        'category': 'Developer Tools',
        'description': 'Browse repositories, create issues, view pull requests, and check '
                       'workflow runs.',
        'recommended': True,
        'color': '#24292E',
        'icon': 'github',
        'tools': [   'create_issue',
                     'search_repos',
                     'get_pull_request',
                     'list_commits',
                     'create_comment']},
    {   'id': 'linear',
        'name': 'Linear',
        'slug': 'linear',
        'category': 'Developer Tools',
        'description': 'Create and update project issues, query sprint cycles, and track bug '
                       'tickets.',
        'recommended': True,
        'color': '#5E6AD2',
        'icon': 'linear',
        'tools': [   'create_issue',
                     'search_issues',
                     'update_issue_status',
                     'list_cycles',
                     'add_comment']},
    {   'id': 'jira',
        'name': 'Jira',
        'slug': 'jira',
        'category': 'Developer Tools',
        'description': 'Search Jira issues with JQL, transition issue statuses, log work, and '
                       'manage sprints.',
        'recommended': True,
        'color': '#0052CC',
        'icon': 'jira',
        'tools': [   'create_issue',
                     'search_issues_jql',
                     'transition_issue',
                     'get_issue',
                     'assign_issue']},
    {   'id': 'notion',
        'name': 'Notion',
        'slug': 'notion',
        'category': 'Knowledge & Docs',
        'description': 'Query workspace databases, search knowledge pages, create docs, and '
                       'append blocks.',
        'recommended': True,
        'color': '#000000',
        'icon': 'notion',
        'tools': [   'query_database',
                     'create_page',
                     'search_pages',
                     'append_block',
                     'update_page']},
    {   'id': 'googledrive',
        'name': 'Google Drive',
        'slug': 'googledrive',
        'category': 'Knowledge & Docs',
        'description': 'Search stored files, list folders, retrieve document text, and '
                       'organize drive files.',
        'recommended': True,
        'color': '#0F9D58',
        'icon': 'googledrive',
        'tools': [   'search_files',
                     'download_file',
                     'list_folders',
                     'create_folder',
                     'share_file']},
    {   'id': 'googlesheets',
        'name': 'Google Sheets',
        'slug': 'googlesheets',
        'category': 'Productivity',
        'description': 'Read spreadsheet cells and ranges, append rows, and update tabular '
                       'tracking data.',
        'recommended': True,
        'color': '#0F9D58',
        'icon': 'googlesheets',
        'tools': [   'read_range',
                     'append_rows',
                     'create_spreadsheet',
                     'update_cells',
                     'get_sheet_values']},
    {   'id': 'hubspot',
        'name': 'HubSpot',
        'slug': 'hubspot',
        'category': 'CRM & Sales',
        'description': 'Search CRM contacts, create sales deals, retrieve company info, and '
                       'log caller notes.',
        'recommended': True,
        'color': '#FF7A59',
        'icon': 'hubspot',
        'tools': [   'search_contacts',
                     'create_deal',
                     'get_company',
                     'log_engagement',
                     'update_contact']},
    {   'id': 'salesforce',
        'name': 'Salesforce',
        'slug': 'salesforce',
        'category': 'CRM & Sales',
        'description': 'Query Salesforce records, create customer leads, update opportunities, '
                       'and manage accounts.',
        'recommended': True,
        'color': '#00A1E0',
        'icon': 'salesforce',
        'tools': [   'query_records',
                     'create_lead',
                     'update_opportunity',
                     'get_account',
                     'create_task']},
    {   'id': 'discord',
        'name': 'Discord',
        'slug': 'discord',
        'category': 'Communication',
        'description': 'Send channel messages, monitor server discussions, send direct '
                       'messages, and manage roles.',
        'recommended': False,
        'color': '#5865F2',
        'icon': 'discord',
        'tools': ['send_channel_message', 'get_guild_members', 'create_dm', 'read_messages']},
    {   'id': 'msteams',
        'name': 'Microsoft Teams',
        'slug': 'msteams',
        'category': 'Communication',
        'description': 'Post messages to team channels, list teams, and send chat alerts '
                       'across Microsoft 365.',
        'recommended': False,
        'color': '#6264A7',
        'icon': 'msteams',
        'tools': [   'send_chat_message',
                     'list_teams',
                     'post_channel_message',
                     'get_chat_history']},
    {   'id': 'zendesk',
        'name': 'Zendesk',
        'slug': 'zendesk',
        'category': 'CRM & Sales',
        'description': 'Lookup customer service tickets, create support tickets, post agent '
                       'replies, and track statuses.',
        'recommended': False,
        'color': '#03363D',
        'icon': 'zendesk',
        'tools': [   'search_tickets',
                     'create_ticket',
                     'update_ticket',
                     'get_user_tickets',
                     'add_comment']},
    {   'id': 'airtable',
        'name': 'Airtable',
        'slug': 'airtable',
        'category': 'Productivity',
        'description': 'Query database bases, create new records, filter rows, and update '
                       'spreadsheet records.',
        'recommended': False,
        'color': '#FCB400',
        'icon': 'airtable',
        'tools': [   'list_records',
                     'create_record',
                     'update_record',
                     'search_base',
                     'delete_record']},
    {   'id': 'twitter',
        'name': 'Twitter / X',
        'slug': 'twitter',
        'category': 'Communication',
        'description': 'Post tweets/updates, search recent tweets, look up public profiles, '
                       'and retrieve timelines.',
        'recommended': False,
        'color': '#000000',
        'icon': 'twitter',
        'tools': [   'post_tweet',
                     'search_recent_tweets',
                     'get_user_profile',
                     'get_user_timeline']}]
)

BY_ID: dict[str, dict] = {c["id"]: c for c in CATALOG}
